# Generated by Django 5.2.8 on 2025-11-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planetarium', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='astronomyshow',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
